# Development environment reusing production and just adding mounts for docker-sync
version: "2"
services:
  someapp:
    environment:
      RAILS_ENV: 'development'
    volumes_from:
      - container:fullexample-sync:rw # will be mounted on /var/www
  otherapp:
    volumes_from:
      - container:simpleexample-sync:rw # will be mounted on /app/code
  appthatproducedata:
    volumes_from:
      - container:unison-dualside-sync:rw # will be mounted on /data

volumes:
  fullexample-sync:
    external: true
  simpleexample-sync:
    external: true
  unison-dualside-sync:
    external: true