# Development environment reusing production and just adding mounts for docker-sync
version: "2"
services:
  rsyncapp:
    environment:
      RAILS_ENV: 'development'
    volumes_from:
      - container:rsync-sync:rw # will be mounted on /var/www
  unisononsidedapp:
    volumes_from:
      - container:unison-onesided-sync:rw # will be mounted on /app/code
  appthatproducedata:
    volumes_from:
      - container:unison-dualside-sync:rw # will be mounted on /data

volumes:
  rsync-sync:
    external: true
  unison-onesided-sync:
    external: true
  unison-dualside-sync:
    external: true