# Development environment reusing production and just adding mounts for docker-sync
version: "2"
services:
  rsyncapp:
    environment:
      RAILS_ENV: 'development'
    volumes_from:
      - container:rsync-sync:rw # will be mounted on /var/www
  unisonapp:
    volumes_from:
      - container:unison-sync:rw # will be mounted on /app/code

volumes:
  rsync-sync:
    external: true
  unison-sync:
    external: true
