language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4

#os: osx

services: docker

before_install:
  - docker pull eugenmayer/unison:hostsync_0.2
  - docker pull eugenmayer/unison:latest
  - docker pull eugenmayer/rsync

script: bundle exec rspec --format=documentation
